Repository prio-data/views_pipeline, pull requests merged in 2024-10, with the labels that each got.

#82 Prevent merge when branch is behind main
  .github/workflows/prevent_merge_when_branch_behind.yml
Labels: improvement

#78 GitHub issue guide pr
  documentation/github_bugfix_issue_template.md
  documentation/github_feature_request_template.md
  documentation/guide_to_issues_on_github.md
Labels: documentation

#87 Add tests for common utils
  common_utils/README.md
  common_utils/set_path.py
  common_utils/tests/test_set_path.py
  common_utils/tests/test_utils_artifacts.py
  common_utils/tests/test_utils_df_to_vol_conversion.py
  common_utils/tests/test_utils_evaluation_metrics.py
  common_utils/tests/test_utils_model_outputs.py
  common_utils/tests/test_utils_wandb.py
  common_utils/utils_cli_parser.py
Labels: improvement

#116 Fix test eval metrics
  common_utils/tests/test_utils_evaluation_metrics.py
  common_utils/tests/test_utils_model_outputs.py
Labels: bug
